apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: apps
spec:
  selector:
    app: node-exporter
  ports:
  - name: http
    protocol: TCP
    port: 9100
    targetPort: 9100
  clusterIP: None # Permet de créer un service headless pour la découverte DNS
